# Generated by Django 4.2.3 on 2023-07-19 17:37

from django.db import migrations, models
import django.utils.translation


class Migration(migrations.Migration):

    dependencies = [
        ("djangocms_alias", "0003_alter_aliasplugin_cmsplugin_ptr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aliascontent",
            name="language",
            field=models.CharField(
                default=django.utils.translation.get_language, max_length=10
            ),
        ),
    ] 